// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { clone } from "./clone.js";
import { compact } from "./compact.js";
import { create } from "./create.js";
import { filter } from "./filter.js";
import { find } from "./find.js";
import { findOr } from "./findOr.js";
import { findOrElse } from "./findOrElse.js";
import { findOrThrow } from "./findOrThrow.js";
import { forEach } from "./forEach.js";
import { get } from "./get.js";
import { getOr } from "./getOr.js";
import { getOrElse } from "./getOrElse.js";
import { getOrThrow } from "./getOrThrow.js";
import { has } from "./has.js";
import { hasAll } from "./hasAll.js";
import { hasAny } from "./hasAny.js";
import { hasNone } from "./hasNone.js";
import { is } from "./is.js";
import { isEmpty } from "./isEmpty.js";
import { isShallowEqual } from "./isShallowEqual.js";
import { map } from "./map.js";
import { mapEach } from "./mapEach.js";
import { mapOr } from "./mapOr.js";
import { mapOrElse } from "./mapOrElse.js";
import { mapOrThrow } from "./mapOrThrow.js";
import { reject } from "./reject.js";
import { remove } from "./remove.js";
import { removeAll } from "./removeAll.js";
import { removeOr } from "./removeOr.js";
import { removeOrElse } from "./removeOrElse.js";
import { removeOrThrow } from "./removeOrThrow.js";
import { set } from "./set.js";

declare namespace Map {
    export {
        clone,
        compact,
        create,
        filter,
        find,
        findOr,
        findOrElse,
        findOrThrow,
        forEach,
        get,
        getOr,
        getOrElse,
        getOrThrow,
        has,
        hasAll,
        hasAny,
        hasNone,
        is,
        isEmpty,
        isShallowEqual,
        map,
        mapEach,
        mapOr,
        mapOrElse,
        mapOrThrow,
        reject,
        remove,
        removeAll,
        removeOr,
        removeOrElse,
        removeOrThrow,
        set,
    }
}

export {
    Map,
}
